name: flutter_app
description: "A new Flutter project."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_native_splash: ^2.4.4
  freezed_annotation: ^3.1.0
  go_router: ^16.2.1
  internal_application:
    path: ../../packages/application
  internal_debug:
    path: ../../packages/debug
  internal_design_theme:
    path: ../../packages/design_theme
  internal_design_ui:
    path: ../../packages/design_ui
  internal_domain_logic:
    path: ../../packages/domain_logic
  internal_domain_model:
    path: ../../packages/domain_model
  internal_infrastructure:
    path: ../../packages/infrastructure
  internal_shared:
    path: ../../packages/shared
  internal_util_ui:
    path: ../../packages/util_ui
  intl: ^0.20.2
  package_info_plus: ^8.3.1
  pub_semver: ^2.2.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  talker_flutter: ^5.0.0
  talker_riverpod_logger: ^5.0.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  flutter_gen_runner: ^5.11.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  go_router_builder: ^3.0.0
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/yumemi_logo.png
    - assets/splash_background.png
    - assets/app_icon.png
    - assets/logo.svg
    - assets/frame.svg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/LOGO.png"
  adaptive_icon_background: "#f3e6f4"

flutter_native_splash:
  color: "#f3e6f4"
  image: assets/app_icon.png
  android: true
  ios: true

  android_12:
    color: "#f3e6f4"
    image: assets/app_icon.png
