name: flutter_app
description: "A new Flutter project."
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.8.0
  flutter: ^3.32.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_native_splash: ^2.4.4
  freezed_annotation: ^3.1.0
  go_router: ^16.2.1
  internal_application:
    path: ../../packages/application
  internal_debug:
    path: ../../packages/debug
  internal_design_theme:
    path: ../../packages/design_theme
  internal_design_ui:
    path: ../../packages/design_ui
  internal_domain_logic:
    path: ../../packages/domain_logic
  internal_domain_model:
    path: ../../packages/domain_model
  internal_infrastructure:
    path: ../../packages/infrastructure
  internal_shared:
    path: ../../packages/shared
  internal_util_ui:
    path: ../../packages/util_ui
  flutter_svg: ^2.0.17
  intl: ^0.20.2
  package_info_plus: ^8.3.1
  pub_semver: ^2.2.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  talker_flutter: ^5.0.0
  talker_riverpod_logger: ^5.0.0
  video_player: ^2.10.1
  lottie: ^3.3.2
  path_drawing: ^1.0.1
  font_awesome_flutter: ^10.12.0
  pinput: ^6.0.1
  url_launcher: ^6.3.2
  app_links: ^7.0.0
  http: ^1.6.0
  mobile_scanner: ^6.0.2
  flutter_markdown: ^0.7.7+1
  image_picker: ^1.0.7
  google_mlkit_barcode_scanning: ^0.14.2
  sign_in_with_apple: ^6.1.1


dev_dependencies:
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  flutter_gen_runner: ^5.11.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  go_router_builder: ^3.0.0
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/yumemi_logo.png
    - assets/splash_background.png
    - assets/app_icon.png
    - assets/LOGO.png
    - assets/logo.svg
    - assets/frame.svg
    - assets/background.png
    - assets/vector_1.svg
    - assets/Layer_1.svg
    - assets/animation.json
    - assets/google_icon.svg
    - assets/facebook_icon.svg
    - assets/apple_icon.svg
    - assets/home_gradient_bg.png
    - assets/banner_image.png
    - assets/community.svg
    - assets/community.png
    - assets/profile.svg
    - assets/cell_illustration.png
    - assets/c1bdd49a-c54a-4c56-9c76-6e8904ff020d.jpeg
    - assets/embryoanimation.json
    - assets/rippleloading.json
    - assets/onboarding2.json
    - assets/onboarding3.json
    # End of assets

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/LOGO.png"
  adaptive_icon_background: "#f3e6f4"

flutter_native_splash:
  color: "#f3e6f4"
  image: assets/app_icon.png
  android: true
  ios: true

  android_12:
    color: "#f3e6f4"
    image: assets/app_icon.png
